sudo: required
services:
  - docker

before_install:
  - docker build -t dmitriynoskov/docker-angular -f Dockerfile.dev .

script:
  - docker run dmitriynoskov/docker-angular npm run test -- --coverage
